### ISSUE TITLE
Add rosette slope option to MineFlow

### ISSUE THREAD

**Issue by am4321** [MineFlowCSM/MineFlow#1]
Add option to calculate slopes using a rosette. Format would be
```
<Code> <Azimuth> <Slope>
<Code> <Azimuth> <Slope> ....
```
Input would also include a code input file corresponding to the block model.
```
<Code> 
<Code>  ...
```

**Comment by MineFlowCSM** [comment]
This is already supported. See examples directory and code re: PrecedencePattern::MinSearch, specifically the 'SlopeDefinition'

**Comment by am4321** [comment]
As I understand a user would be generating a precedence file from the rosette and block codes. This is used as an input to the program as shown in the example.
Can you please add a comment or an example on how to calculate the precedence file given the rosette and block code file using the PrecedencePattern::MinSearch.
